In [1]:
#numerical python
#list ---> 4000 / matrix---> 1000x1000

In [2]:
import numpy as np

In [3]:
np.__version__

'1.22.3'

In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
d = a.ndim
d

1

In [8]:
s = a.size
s

3

In [10]:
sh = a.shape
sh
#1x3

(3,)

In [14]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype=np.int32)

bd = b.ndim
bd

2

In [15]:
bs = b.shape
bs

(2, 3)

In [16]:
bsi = b.size
bsi

6

In [17]:
bdt = b.dtype
bdt

dtype('int32')

In [18]:
#[[1, 2, 3], [4, 5, 6]]
#house : [area, floor, age]
#house1: [25, 3, 45]
#house2 = [148, 1, 3]...

#1, 2, 3
#4, 5, 6
#...

In [20]:
z = np.zeros((2, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
o = np.ones((4, 5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
f = np.full((2,7), 8)
f

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [30]:
ar = np.arange(0, 10, 2)
ar

array([0, 2, 4, 6, 8])

In [25]:
ls = np.linspace(0, 1, 5)
ls

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]], dtype=np.int32)
a = b.astype(np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [31]:
v = np.arange(1, 13)
print(v)
k = v.reshape(3, 4)
k

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
k2 = v.reshape(4, 4)
k2

ValueError: cannot reshape array of size 12 into shape (4,4)