In [1]:
import numpy as np 

## View

In [2]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])

In [3]:
a.ndim

2

In [4]:
b = a[0:, 0:2]
b

array([[1, 2],
       [4, 5]])

In [5]:
b[0, 0] = 0
b

array([[0, 2],
       [4, 5]])

In [6]:
b[0, 0] = b[0, 0] + 1
b

array([[1, 2],
       [4, 5]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6]])

## Copy

In [8]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
b = a[0:, 0:2].copy()
b[0, 0] = 0

print(b)
print(a)

[[0 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


In [10]:
b

array([[1, 2],
       [4, 5]])

## SUM

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
t = np.sum(a)
t

21

In [11]:
v = np.sum(a, axis=0) #axis=0 --> columns
v

array([5, 7, 9])

In [13]:
h = np.sum(a, axis=1) #axis=1 --> rows
h

array([ 6, 15])

## Mean

In [14]:
k = np.array([1, 2, 3])
average = np.mean(k)
average

2.0

In [15]:
u = np.array([[1, 2, 3], 
             [4, 5, 6]])
avg_2d = np.mean(u) # (1+2+3+4+5+6 )/6
avg_2d

3.5

In [16]:
avg_2d_col_mean = np.mean(u, axis=0)
avg_2d_col_mean  # (1+4)/2 : 2.5

array([2.5, 3.5, 4.5])

In [19]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[11, 12, 13], [14, 15, 16]]
])

In [20]:
avg_3d = np.mean(m_3d)
avg_3d

8.5

In [21]:
avg_3d_axis0 = np.mean(m_3d, axis=0)
avg_3d_axis0

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [22]:
avg_3d_axis2 = np.mean(m_3d, axis=2)
avg_3d_axis2

array([[ 2.,  5.],
       [12., 15.]])

## Var

In [23]:
g = np.array([1, 2, 3])
var_g = np.var(g)
var_g

0.6666666666666666

## std

In [24]:
h = np.array([14, 15, 16])
std_h = np.std(h)
std_h

0.816496580927726

## prod

In [25]:
h = np.array([14, 15, 16])
prod_h = np.prod(h)
prod_h

3360

## min / max

In [26]:
h = np.array([14, 15, 16])
h_min = np.min(h)
h_min

14

In [27]:
h_max = np.max(h)
h_max

16

In [28]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[11, 12, 13], [14, 15, 16]]
])

print(np.max(m_3d))
print(np.min(m_3d))

16
1


In [31]:
m_3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[11, 12, 13], [14, 15, 16]]
])

print(np.amax(m_3d , axis=0))
print(np.amin(m_3d))

[[11 12 13]
 [14 15 16]]
1


In [34]:
u = np.array([[1, 2, 3], 
             [4, 0, 0]])
np.amax(u, axis=0)

#4
#2
#3

array([4, 2, 3])

In [36]:
u = np.array([[1, 2, 3], 
             [4, 0, 0]])
np.amax(u, axis=1)

#3
#4

array([3, 4])

In [35]:
# The End